[package]
name = "envin"
description = "Displays information about your Rust environment"
license = "MIT"
version = "0.0.2"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
sysinfo = "0.32.0"
rustc_version = "0.4.0"
which = "4.4.0"
toml = "0.8.19"